"""fsnb_matcher: add items

Revision ID: 940ec7a6bbce
Revises: 87f35af16311
Create Date: 2025-12-16 13:47:56.185360

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "940ec7a6bbce"
down_revision: Union[str, Sequence[str], None] = "87f35af16311"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_permissions_profile_id"),
        "permissions",
        ["profile_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.drop_index(op.f("ix_permissions_profile_id"), table_name="permissions")
    # ### end Alembic commands ###
