"""train_feedback_tables

Revision ID: 5390851f3bfd
Revises: e306c008d156
Create Date: 2025-12-23 15:10:33.380230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5390851f3bfd"
down_revision: Union[str, Sequence[str], None] = "e306c008d156"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback_sessions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_name", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_sessions")),
    )
    op.create_table(
        "training_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("base_model", sa.Text(), nullable=False),
        sa.Column(
            "data_spec",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("artifacts_path", sa.Text(), nullable=True),
        sa.Column(
            "metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "status", sa.Text(), server_default="running", nullable=False
        ),
        sa.Column("log_path", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_runs")),
    )
    op.create_index(
        "ix_training_runs_mode_started_at",
        "training_runs",
        ["mode", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_training_runs_started_at"),
        "training_runs",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        "ix_training_runs_status", "training_runs", ["status"], unique=False
    )
    op.create_table(
        "feedback_rows",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=False),
        sa.Column("units_in", sa.Text(), nullable=True),
        sa.Column("qty_in", sa.Text(), nullable=True),
        sa.Column(
            "norm_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "is_trusted", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["feedback_sessions.id"],
            name=op.f("fk_feedback_rows_session_id_feedback_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_rows")),
    )
    op.create_index(
        op.f("ix_feedback_rows_created_at"),
        "feedback_rows",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_rows_is_trusted"),
        "feedback_rows",
        ["is_trusted"],
        unique=False,
    )
    op.create_index(
        "ix_feedback_rows_session_created_at",
        "feedback_rows",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_rows_session_id"),
        "feedback_rows",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "feedback_candidates",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("row_id", sa.BigInteger(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column(
            "shown", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("fk_feedback_candidates_item_id_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["row_id"],
            ["feedback_rows.id"],
            name=op.f("fk_feedback_candidates_row_id_feedback_rows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_candidates")),
        sa.UniqueConstraint(
            "row_id",
            "item_id",
            "model_name",
            name="uq_feedback_candidates_row_item_model",
        ),
    )
    op.create_index(
        op.f("ix_feedback_candidates_item_id"),
        "feedback_candidates",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_candidates_row_id"),
        "feedback_candidates",
        ["row_id"],
        unique=False,
    )
    op.create_index(
        "ix_feedback_candidates_row_rank",
        "feedback_candidates",
        ["row_id", "rank"],
        unique=False,
    )
    op.create_table(
        "feedback_labels",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("row_id", sa.BigInteger(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("selected_item_id", sa.Integer(), nullable=True),
        sa.Column(
            "negatives",
            postgresql.ARRAY(sa.Integer()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "is_trusted", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["row_id"],
            ["feedback_rows.id"],
            name=op.f("fk_feedback_labels_row_id_feedback_rows"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["selected_item_id"],
            ["items.id"],
            name=op.f("fk_feedback_labels_selected_item_id_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_labels")),
    )
    op.create_index(
        op.f("ix_feedback_labels_created_at"),
        "feedback_labels",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_labels_is_trusted"),
        "feedback_labels",
        ["is_trusted"],
        unique=False,
    )
    op.create_index(
        "ix_feedback_labels_label", "feedback_labels", ["label"], unique=False
    )
    op.create_index(
        "ix_feedback_labels_row_created_at",
        "feedback_labels",
        ["row_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_labels_row_id"),
        "feedback_labels",
        ["row_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_labels_selected_item_id"),
        "feedback_labels",
        ["selected_item_id"],
        unique=False,
    )
    op.create_table(
        "training_run_rows",
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("row_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),

        sa.ForeignKeyConstraint(
            ["row_id"],
            ["feedback_rows.id"],
            name=op.f("fk_training_run_rows_row_id_feedback_rows"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["training_runs.id"],
            name=op.f("fk_training_run_rows_run_id_training_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "run_id", "row_id", name=op.f("pk_training_run_rows")
        ),
    )
    op.create_index(
        "ix_training_run_rows_row_id",
        "training_run_rows",
        ["row_id"],
        unique=False,
    )
    op.create_index(
        "ix_training_run_rows_run_id",
        "training_run_rows",
        ["run_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        "ix_training_run_rows_run_id", table_name="training_run_rows"
    )
    op.drop_index(
        "ix_training_run_rows_row_id", table_name="training_run_rows"
    )
    op.drop_table("training_run_rows")
    op.drop_index(
        op.f("ix_feedback_labels_selected_item_id"),
        table_name="feedback_labels",
    )
    op.drop_index(
        op.f("ix_feedback_labels_row_id"), table_name="feedback_labels"
    )
    op.drop_index(
        "ix_feedback_labels_row_created_at", table_name="feedback_labels"
    )
    op.drop_index("ix_feedback_labels_label", table_name="feedback_labels")
    op.drop_index(
        op.f("ix_feedback_labels_is_trusted"), table_name="feedback_labels"
    )
    op.drop_index(
        op.f("ix_feedback_labels_created_at"), table_name="feedback_labels"
    )
    op.drop_table("feedback_labels")
    op.drop_index(
        "ix_feedback_candidates_row_rank", table_name="feedback_candidates"
    )
    op.drop_index(
        op.f("ix_feedback_candidates_row_id"), table_name="feedback_candidates"
    )
    op.drop_index(
        op.f("ix_feedback_candidates_item_id"),
        table_name="feedback_candidates",
    )
    op.drop_table("feedback_candidates")
    op.drop_index(
        op.f("ix_feedback_rows_session_id"), table_name="feedback_rows"
    )
    op.drop_index(
        "ix_feedback_rows_session_created_at", table_name="feedback_rows"
    )
    op.drop_index(
        op.f("ix_feedback_rows_is_trusted"), table_name="feedback_rows"
    )
    op.drop_index(
        op.f("ix_feedback_rows_created_at"), table_name="feedback_rows"
    )
    op.drop_table("feedback_rows")
    op.drop_index("ix_training_runs_status", table_name="training_runs")
    op.drop_index(
        op.f("ix_training_runs_started_at"), table_name="training_runs"
    )
    op.drop_index(
        "ix_training_runs_mode_started_at", table_name="training_runs"
    )
    op.drop_table("training_runs")
    op.drop_table("feedback_sessions")
    # ### end Alembic commands ###
